master:
  push:
    - runner:
        tags: cnb:arch:amd64
        cpus: 64
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          imports:
            - https://cnb.cool/XMZZUZHI/key/-/blob/main/Github.yml
          settings:
            target_url: https://github.com/xiaomizhoubaobei/MZAPI-nest.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
